language: php
php:
  - 5.3
  - 5.4
before_script:
  - mkdir logs
  - chmod 777 logs
  - mysql -e 'create database buckutt_test;'
  - php db.php migrations:migrate --write-sql
  - mysql -u root buckutt_test < doctrine_migration_*.sql
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source --no-interaction
  - cd tests/
  - mkdir logs
  - chmod 777 logs
  - cp config.inc.dist.php config.inc.php
  - cd ..
script: ./tests/run_all.sh


